# Generated by Django 4.2.3 on 2023-07-29 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('restype', models.IntegerField(choices=[(0, 'Detailed Notes'), (1, 'Tools'), (2, 'Revision Notes'), (3, 'Formula Sheets'), (4, 'Concept Clarification'), (5, 'Other')], default=0)),
                ('resourcelink', models.URLField(blank=True, max_length=1000, null=True, verbose_name='ResourceURLs')),
                ('embedlink', models.URLField(blank=True, max_length=1000, null=True, verbose_name='VideoURLs')),
                ('affiliateflag', models.BooleanField(default=False, verbose_name='Paid Promotion')),
                ('author', models.ForeignKey(on_delete=models.SET('Deleted User'), related_name='resource_entries', to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ResourceLibrary.level')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ResourceLibrary.subject')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('email', models.TextField(max_length=50)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ResourceLibrary.entry')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
