# Generated by Django 4.2.3 on 2023-07-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceLibrary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='customhtml',
            field=models.TextField(blank=True, null=True, verbose_name='Custom HTML Code'),
        ),
        migrations.AddField(
            model_name='entry',
            name='extracontrib',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Extra Contributor Credits'),
        ),
    ]
